# Setup
title:               Uncertainty Toolbox
tagline:             ''
description:         'Website for <a href="https://github.com/uncertainty-toolbox/uncertainty-toolbox" target="_blank">Uncertainty Toolbox</a>.'
url:                 http://uncertainty-toolbox.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty
port: 4444

# About/contact
author:
  name:              Uncertainty Toolbox Team
  url:               https://github.com/uncertainty-toolbox/uncertainty-toolbox

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
